framework:
  messenger:
    transports:
      order_events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          exchange:
            name: order_exchange_direct
            type: direct
          queues: {}

      product_events:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          exchange:
            name: product_exchange_direct
            type: direct
          queues:
            order_service_queue: ~

    routing:
      Shared\Bundle\Messaging\OrderMessage: order_events
