networks:
  app_network:
    external: true

services:
  order_service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: order_service
    depends_on:
      - order_db
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://symfony:symfony@order_db:5432/order_db?serverVersion=15&charset=utf8"
      MESSENGER_TRANSPORT_DSN: amqp://guest:guest@rabbitmq:5672/%2f
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: php -S 0.0.0.0:8000 -t public
    networks:
      - app_network

  order_db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  order_db_data:
